# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'price.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys,os,time
from selenium import webdriver
from bs4 import BeautifulSoup
from datetime import datetime
import win32com.client

if getattr(sys, 'frozen', False):
    Chrome_path = os.path.join(sys._MEIPASS, "ChromeDriver.exe")
    driver = webdriver.Chrome(Chrome_path)
else:#
    driver=webdriver.Chrome()

excel=win32com.client.Dispatch("Excel.Application")
excel.Visible=False
wb=excel.workbooks.Open(os.getcwd()+'\price.xlsx')



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(608, 475)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 563, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AssacomButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.AssacomButton.setObjectName("AssacomButton")
        self.horizontalLayout.addWidget(self.AssacomButton)
        self.BlueitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.BlueitButton.setObjectName("BlueitButton")
        self.horizontalLayout.addWidget(self.BlueitButton)
        self.OhmypcButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.OhmypcButton.setObjectName("OhmypcButton")
        self.horizontalLayout.addWidget(self.OhmypcButton)
        self.ComzipButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ComzipButton.setObjectName("ComzipButton")
        self.horizontalLayout.addWidget(self.ComzipButton)
        self.WanggapcButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.WanggapcButton.setObjectName("WanggapcButton")
        self.horizontalLayout.addWidget(self.WanggapcButton)
        self.PopconpcButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PopconpcButton.setObjectName("PopconpcButton")
        self.horizontalLayout.addWidget(self.PopconpcButton)
        self.CommawangButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CommawangButton.setObjectName("CommawangButton")
        self.horizontalLayout.addWidget(self.CommawangButton)
        self.ExcelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ExcelButton.setObjectName("ExcelButton")
        self.horizontalLayout.addWidget(self.ExcelButton)
        self.ExcelQuitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ExcelQuitButton.setObjectName("ExcelQuitButton")
        self.horizontalLayout.addWidget(self.ExcelQuitButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 160, 531, 251))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.CPUText = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.CPUText.setObjectName("CPUText")
        self.horizontalLayout_2.addWidget(self.CPUText)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.GPUText = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.GPUText.setObjectName("GPUText")
        self.horizontalLayout_2.addWidget(self.GPUText)
        self.AllButton = QtWidgets.QPushButton(self.centralwidget)
        self.AllButton.setGeometry(QtCore.QRect(260, 120, 75, 23))
        self.AllButton.setObjectName("AllButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 608, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_2.addWidget(self.plainTextEdit)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AssacomButton.setText(_translate("MainWindow", "아싸컴"))
        self.AssacomButton.clicked.connect(self.assacom)
        self.BlueitButton.setText(_translate("MainWindow", "블루아이티"))
        self.BlueitButton.clicked.connect(self.blueit)
        self.OhmypcButton.setText(_translate("MainWindow", "오마이피씨"))
        self.OhmypcButton.clicked.connect(self.ohmypc)
        self.ComzipButton.setText(_translate("MainWindow", "컴집"))
        self.ComzipButton.clicked.connect(self.comzip)
        self.WanggapcButton.setText(_translate("MainWindow", "왕가피씨"))
        self.WanggapcButton.clicked.connect(self.wanggapc)
        self.PopconpcButton.setText(_translate("MainWindow", "팝콘피씨"))
        self.PopconpcButton.clicked.connect(self.popconpc)
        self.CommawangButton.setText(_translate("MainWindow", "컴마왕"))
        self.CommawangButton.clicked.connect(self.commawang)
        self.ExcelButton.setText(_translate("MainWindow", "엑셀"))
        self.ExcelButton.clicked.connect(self.Excel)
        self.ExcelQuitButton.setText(_translate("MainWindow", "엑셀끝내기"))
        self.ExcelQuitButton.clicked.connect(self.ExcelQuit)
        self.label.setText(_translate("MainWindow", "CPU :"))
        self.label_2.setText(_translate("MainWindow", "GPU"))
        self.AllButton.setText(_translate("MainWindow", "모두수집"))
        self.label_3.setText(_translate("MainWindow", "로그"))
        self.AllButton.clicked.connect(self.All)

    def All(self):
        self.assacom()
        self.blueit()
        self.ohmypc()
        self.comzip()
        self.wanggapc()
        self.popconpc()
        self.commawang()
        self.Excel()



    def ExcelQuit(self):
        excel.quit()

    ##엑셀
    def Excel(self):
        
        ws1=wb.Worksheets('가격비교')
        ws2=wb.Worksheets('아싸컴')
        ws3=wb.Worksheets('블루아이티')
        ws4=wb.Worksheets('오마이피씨')
        ws5=wb.Worksheets('컴집')
        ws6=wb.Worksheets('왕가피씨')
        ws7=wb.Worksheets('팝콘피씨')
        ws8=wb.Worksheets('컴마왕')
        ws1.Cells(1,3).Value="상품제목"
        ws1.Cells(1,4).Value="가격"
        ws1.Cells(1,5).Value="CPU"
        ws1.Cells(1,6).Value="cpu cooler"
        ws1.Cells(1,7).Value="mainboard"
        ws1.Cells(1,8).Value="ram"
        ws1.Cells(1,9).Value="SSD"
        ws1.Cells(1,10).Value="HDD"
        ws1.Cells(1,11).Value="VGA"
        ws1.Cells(1,12).Value="power"
        ws1.Cells(1,13).Value="case"

        cpus=[]
        vgas=[]
        cpus=self.CPUText.toPlainText().split()
        vgas=self.GPUText.toPlainText().split()


        ws1=wb.Worksheets('가격비교')
        ws2=wb.Worksheets('아싸컴')
        ws3=wb.Worksheets('블루아이티')
        ws4=wb.Worksheets('오마이피씨')
        ws5=wb.Worksheets('컴집')
        ws6=wb.Worksheets('왕가피씨')
        ws7=wb.Worksheets('팝콘피씨')
        ws8=wb.Worksheets('컴마왕')
        origin=2 ## 가격비교 번호
        k=2 ##부품 입력값

        ##비교
        ws1.Cells(origin,3).Value='아싸컴'
        ws1.Cells(origin,3).Interior.ColorIndex = 10
        origin+=1
        ##가격비교시트에서 CPU,VGA 등록
        for cpu,vga in zip(cpus,vgas):
            ws1.Cells(k,1).Value=cpu
            ws1.Cells(k,2).Value=vga
            i=2
            while(1):
                if ws2.Cells(i,5).Value is None:
                    break
                if cpu in ws2.Cells(i,5).Value and vga in ws2.Cells(i,8).Value:
                    ws1.Cells(origin,3).value=ws2.Cells(i,1).Value #상품제목
                    ws1.Cells(origin,4).value=ws2.Cells(i,3).Value ##가격
                    ws1.Cells(origin,5).Value=ws2.Cells(i,5).Value ##cpu
                    ws1.Cells(origin,8).Value=ws2.Cells(i,6).Value ## Ram
                    ws1.Cells(origin,9).Value=ws2.Cells(i,7).Value ## SSD
                    ws1.Cells(origin,11).Value=ws2.Cells(i,8).Value ## VGA
                    origin+=1
                i+=1
            k+=1
            origin+=1

        ws1.Cells(origin,3).Value="블루아이티"
        ws1.Cells(origin,3).Interior.ColorIndex = 10
        origin+=1
        for cpu,vga in zip(cpus,vgas):
            i=2
            while(1):
                if ws3.Cells(i,3).Value is None:
                    break
                if (cpu in ws3.Cells(i,3).Value and (vga in ws3.Cells(i,6).Value or vga in ws3.Cells(i,7).Value)):
                    ws1.Cells(origin,3).Value=ws3.Cells(i,1).Value #상품제목
                    ws1.Cells(origin,5).Value=ws3.Cells(i,3).Value ##CPU
                    ws1.Cells(origin,4).Value=ws3.Cells(i,20).Value##가격
                    for j in range(4,19):##나머지
                        ws1.Cells(origin,j+2).Value=ws3.Cells(i,j).Value
                    origin+=1
                i+=1
            origin+=1

        ws1.Cells(origin,3).Value="오마이피씨"
        ws1.Cells(origin,3).Interior.ColorIndex = 10
        origin+=1
        for cpu,vga in zip(cpus,vgas):
            i=2
            while(1):
                if ws4.Cells(i,4).Value is None:
                    break
                if (cpu in ws4.Cells(i,4).Value or cpu in ws4.Cells(i,5).Value) and (vga in ws4.Cells(i,9).Value or vga in ws4.Cells(i,10).Value):
                    ws1.Cells(origin,3).Value=ws4.Cells(i,1).Value##상품제목
                    ws1.Cells(origin,4).Value=ws4.Cells(i,2).Value##가격
                    for j in range(3,19):##나머지
                        ws1.Cells(origin,j+2).Value=ws4.Cells(i,j).Value
                    origin+=1
                i+=1
            origin+=1

        ws1.Cells(origin,3).Value="컴집"
        ws1.Cells(origin,3).Interior.ColorIndex = 10
        origin+=1
        for cpu,vga in zip(cpus,vgas):
            i=2
            while(1):
                if ws5.Cells(i,3).Value is None:
                    break
                if cpu in ws5.Cells(i,3).Value and vga in ws5.Cells(i,9).Value:
                    ws1.Cells(origin,3).Value=ws5.Cells(i,1).Value ##상품제목
                    ws1.Cells(origin,4).Value=ws5.Cells(i,2).Value#가격
                    ws1.Cells(origin,5).Value=ws5.Cells(i,3).Value ##CPU
                    ws1.Cells(origin,6).value=ws5.Cells(i,4).Value ##쿨러
                    ws1.Cells(origin,7).Value=ws5.Cells(i,5).Value ##메인보드
                    ws1.Cells(origin,8).Value=ws5.Cells(i,6).Value ##RAM
                    ws1.Cells(origin,9).Value=ws5.Cells(i,7).Value ##SSD
                    ws1.Cells(origin,10).Value=ws5.Cells(i,8).Value ##HDD
                    ws1.Cells(origin,11).Value=ws5.Cells(i,9).Value ##VGA
                    ws1.Cells(origin,13).Value=ws5.Cells(i,13).Value ##케이스
                    ws1.Cells(origin,12).Value=ws5.Cells(i,14).Value ##파워
                    origin+=1
                i+=1
            origin+=1

        ws1.Cells(origin,3).Value="왕가피씨"
        ws1.Cells(origin,3).Interior.ColorIndex = 10
        origin+=1
        for cpu,vga in zip(cpus,vgas):
            i=2
            while(1):
                if ws6.Cells(i,4).Value is None:
                    break
                if cpu in ws6.Cells(i,4).Value and vga in ws6.Cells(i,8).Value:
                    ws1.Cells(origin,3).Value=ws6.Cells(i,1).Value ##상품제목
                    ws1.Cells(origin,4).value=ws6.Cells(i,2).Value##가격
                    ws1.Cells(origin,5).Value=ws6.Cells(i,4).Value##CPU
                    ws1.Cells(origin,6).Value=ws6.Cells(i,5).Value ##쿨러
                    ws1.Cells(origin,8).Value=ws6.Cells(i,6).Value #RAM
                    ws1.Cells(origin,7).Value=ws6.Cells(i,7).Value ##메인보드
                    ws1.Cells(origin,11).Value=ws6.Cells(i,8).Value ##VGA
                    ws1.Cells(origin,9).Value=ws6.Cells(i,9).Value ##ssd
                    ws1.Cells(origin,10).Value=ws6.Cells(i,10).Value ##HDD
                    ws1.Cells(origin,12).Value=ws6.Cells(i,13).Value ##power
                    ws1.Cells(origin,13).Value=ws6.Cells(i,14).Value ##케이스
                    origin+=1
                i+=1
            origin+=1
            

        ws1.Cells(origin,3).Value="팝콘피씨"
        ws1.Cells(origin,3).Interior.ColorIndex = 10
        origin+=1
        for cpu,vga in zip(cpus,vgas):
            i=2
            while(1):
                if ws7.Cells(i,3).Value is None:
                    break
                if (cpu in ws7.Cells(i,4).Value or cpu in ws7.Cells(i,5).Value) and (vga in ws7.Cells(i,8).Value or vga in ws7.Cells(i,9).Value):
                    ws1.Cells(origin,3).Value=ws7.Cells(i,1).Value#상품이름
                    ws1.Cells(origin,4).Value=ws7.Cells(i,2).Value#가격
                    for j in range(4,21):##나머지
                        ws1.Cells(origin,j+1).Value=ws7.Cells(i,j).Value
                    origin+=1
                i+=1
            origin+=1

        ws1.cells(origin,3).Value="컴마왕"
        ws1.Cells(origin,3).Interior.ColorIndex = 10
        origin+=1
        for cpu,vga in zip(cpus,vgas):
            i=2
            while(1):
                if ws8.Cells(i,4).Value is None:
                    break
                if (cpu in ws8.Cells(i,4).Value or cpu in ws8.Cells(i,5).value) and (vga in ws8.Cells(i,8).Value or vga in ws8.Cells(i,9).Value):
                    ws1.Cells(origin,3).Value=ws8.Cells(i,1).Value ##상품이름
                    ws1.Cells(origin,4).Value=ws8.Cells(i,2).Value##가격
                    for j in range(4,15):##나머지
                        ws1.Cells(origin,j+1).Value=ws8.Cells(i,j).Value
                    origin+=1
                i+=1
            origin+=1

        wb.SaveAs(os.getcwd()+'\\'+str(datetime.today().strftime('%Y-%m-%d'))+'.xlsx')
        self.plainTextEdit.appendPlainText(time.strftime('%H%M%S')+"엑셀완료")

        return True

        ##아싸컴
    def assacom(self):    
        i=2
        j=1
        ws=wb.Worksheets('아싸컴')
        

        driver.get("https://www.assacom.com/shop/new_sub/all_product.htm?p=top")
        time.sleep(2)
        html=driver.page_source
        soup=BeautifulSoup(html,'html.parser')
        while(1):
            for name in soup.select('div.node_pro > p > a'):
                ws.cells(i,j).Value=name.text.strip()
                j+=1
                if j==4:
                    i+=1
                    j=1
            i=2
            j=4
            for k in range(2,7):
                for table in soup.select('tbody > tr:nth-child('+str(k)+') > td:nth-child(2) > a'):
                    ws.cells(i,j).Value=table.text.strip()
                    i+=1
                i=2
                j+=1
            break

        self.plainTextEdit.appendPlainText(time.strftime('%H%M%S')+"아싸컴완료")

        return  True

    ##블루아이티

    def blueit(self):
        cnt=0
        ws=wb.Worksheets('블루아이티')
        j=2
        url=(['https://www.blueit.co.kr/skin/shop/basicwide/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=&game=&sprice=300000&eprice=400000&event_no=&pc_title=30~40만원대',
        'https://www.blueit.co.kr/skin/shop/basicwide/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=&game=&sprice=400000&eprice=500000&event_no=&pc_title=40~50만원대',
        'https://www.blueit.co.kr/skin/shop/basicwide/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=&game=&sprice=500000&eprice=600000&event_no=&pc_title=50~60만원대',
        'https://www.blueit.co.kr/skin/shop/basicwide/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=&game=&sprice=600000&eprice=700000&event_no=&pc_title=60~70만원대',
        'https://www.blueit.co.kr/skin/shop/basicwide/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=&game=&sprice=700000&eprice=800000&event_no=&pc_title=70~80만원대',
        'https://www.blueit.co.kr/skin/shop/basicwide/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=&game=&sprice=800000&eprice=900000&event_no=&pc_title=80~90만원대',
        'https://www.blueit.co.kr/skin/shop/basicwide/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=&game=&sprice=900000&eprice=1000000&event_no=&pc_title=90~100만원대',
        'https://www.blueit.co.kr/skin/shop/basicwide/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=&game=&sprice=1000000&eprice=1200000&event_no=&pc_title=100~120만원대',
        'https://www.blueit.co.kr/skin/shop/basicwide/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=&game=&sprice=1200000&eprice=1500000&event_no=&pc_title=120~150만원대',
        'https://www.blueit.co.kr/skin/shop/basicwide/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=&game=&sprice=1500000&eprice=2000000&event_no=&pc_title=150~200만원대',
        'https://www.blueit.co.kr/skin/shop/basicwide/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=&game=&sprice=2000000&eprice=3000000&event_no=&pc_title=200~300만원대',
        'https://www.blueit.co.kr/skin/shop/basicwide/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=&game=&sprice=3000000&eprice=10000000&event_no=&pc_title=300만원대 이상'])

        for i in url:
            k=2
            driver.get(i)
            time.sleep(2)
            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            for name in soup.select('body > form > table > tbody > tr > td > table:nth-child(3) > tbody > tr > td > table > tbody > tr > td > table:nth-child(1) > tbody > tr > td > b > a > font:nth-child(1)'):
                ws.Cells(j,1).Value=name.text.strip()
                j+=1
                cnt+=1
            j-=cnt
            cnt=0
            for info in soup.select('body > form > table > tbody > tr > td > table:nth-child(3) > tbody > tr > td > table > tbody > tr > td> table:nth-child(2) > tbody > tr > td > span'):
                ws.Cells(j,k).Value=info.text.strip()
                if '완본체 PC 사은품' in info.text.strip():
                    j+=1
                    cnt+=1
                    k=1
                k+=1
            j-=cnt
            cnt=0
            for price in soup.select('body > form > table > tbody > tr > td > table:nth-child(3) > tbody > tr > td > table > tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(2) > td > a'):
                ws.Cells(j,20).Value=price.text.strip()
                j+=1

        self.plainTextEdit.appendPlainText(time.strftime('%H%M%S')+"블루아이티완료")
        return True

    ##오마이피씨

    def ohmypc(self):

        ws=wb.Worksheets('오마이피씨')
        i=2
        j=3
        cnt=0

        url=(['https://www.omypc.co.kr/shopuser/goods/productList.html?largeno=1&middleno=1&kind=normal',
        'https://www.omypc.co.kr/shopuser/goods/productList.html?largeno=1&middleno=3&kind=normal',
        'https://www.omypc.co.kr/shopuser/goods/productList.html?largeno=1&middleno=2&kind=normal',
        'https://www.omypc.co.kr/shopuser/goods/productList.html?largeno=1&middleno=5&kind=normal',
        'https://www.omypc.co.kr/shopuser/goods/productList.html?largeno=49&kind=normal',
        'https://www.omypc.co.kr/shopuser/goods/productList.html?largeno=1&middleno=6&kind=normal'])

        for link in url:
            driver.get(link)
            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            for name in soup.select('table > tbody > tr > td > table > tbody > tr > td > b > a'):
                ws.Cells(i,1).Value=name.text.strip()
                i+=1
                cnt+=1
            i-=cnt
            for price in soup.select('td:nth-child(2) > table > tbody > tr:nth-child(7) > td > table > tbody > tr > td'):
                ws.Cells(i,2).Value=price.text.strip()
                i+=1
            i-=cnt
            for info in soup.select('table > tbody > tr:nth-child(10) > td > table > tbody > tr > td:nth-child(2)'):
            #for info in soup.select('table:nth-child('+str(j)+') > tbody > tr:nth-child(10) > td:nth-child('+str(k)+') > table > tbody > tr > td:nth-child(2)'):
                ws.Cells(i,j).Value=info.text.strip()
                j+=1
                if '[사은품]' in info.text.strip():
                    i+=1
                    j=3
            cnt=0

        self.plainTextEdit.appendPlainText(time.strftime('%H%M%S')+"오마이피씨완료")
        return True

    ## 컴집

    def comzip(self):
        i=2
        cnt=0
        j=2
        ws=wb.Worksheets("컴집")

        url=(['https://www.comzip.co.kr/shopuser/goods/productList.html?largeno=152&middleno=1&kind=normal',
        'https://www.comzip.co.kr/shopuser/goods/productList.html?largeno=152&middleno=2&kind=normal',
        'https://www.comzip.co.kr/shopuser/goods/productList.html?largeno=152&middleno=3&kind=normal',
        'https://www.comzip.co.kr/shopuser/goods/productList.html?largeno=152&middleno=4&kind=normal',
        'https://www.comzip.co.kr/shopuser/goods/productList.html?largeno=152&middleno=5&kind=normal',
        'https://www.comzip.co.kr/shopuser/goods/productList.html?largeno=152&middleno=6&kind=normal'])

        for link in url:
            driver.get(link)
            time.sleep(2)
            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            for name in soup.select('td:nth-child(2) > table > tbody > tr:nth-child(3) > td > table > tbody > tr > td > b > a'):
                ws.Cells(i,1).Value=name.text.strip()
                i+=1
                cnt+=1
            i-=cnt
            for price in soup.select('td:nth-child(2) > table > tbody > tr:nth-child(7) > td > table > tbody > tr > td'):
                ws.Cells(i,2).Value=price.text.strip()
                i+=1
            i-=cnt
            for info in soup.select('td:nth-child(2) > table > tbody > tr:nth-child(10) > td > table > tbody > tr > td:nth-child(2)'):
                ws.Cells(i,j).Value=info.text.strip()
                j+=1
                if '3년무상' in info.text.strip():
                    i+=1
                    j=3
            cnt=0
        
        self.plainTextEdit.appendPlainText(time.strftime('%H%M%S')+"컴집완료")
        return True

    ## 왕가피씨

    def wanggapc(self):
        ws=wb.Worksheets('왕가피씨')
        i=2
        cnt=0
        j=3

        url=(['https://www.wanggapc.com/shopuser/goods/productList.html?kind=normal&largeno=65&middleno=1&smallno=0',
        'https://www.wanggapc.com/shopuser/goods/productList.html?kind=normal&largeno=65&middleno=2&smallno=0',
        'https://www.wanggapc.com/shopuser/goods/productList.html?kind=normal&largeno=65&middleno=3&smallno=0',
        'https://www.wanggapc.com/shopuser/goods/productList.html?largeno=65&middleno=4&kind=normal'])

        for link in url:
            driver.get(link)
            time.sleep(2)
            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            for name in soup.select('td:nth-child(2) > table > tbody > tr:nth-child(3) > td > table > tbody > tr > td'):
                ws.Cells(i,1).Value=name.text.strip()
                i+=1
                cnt+=1
            i-=cnt
            for price in soup.select('td:nth-child(2) > table > tbody > tr:nth-child(7) > td > table > tbody > tr > td'):
                ws.Cells(i,2).Value=price.text.strip()
                i+=1
            i-=cnt
            for info in soup.select('td:nth-child(2) > table > tbody > tr:nth-child(10) > td > table > tbody > tr > td:nth-child(2)'):
                ws.Cells(i,j).Value=info.text.strip()
                j+=1
                if '윈도우' in info.text.strip():
                    i+=1
                    j=3
            cnt=0

        self.plainTextEdit.appendPlainText(time.strftime('%H%M%S')+"왕가피씨완료")
        return True

    ##팝콘피씨

    def popconpc(self):
        ws=wb.Worksheets('팝콘피씨')

        i=2
        cnt=0
        j=3
        page=3

        url=(['http://popcornpc.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=11015&game=&sprice=&eprice=&event_no=&pc_title=완제품컴퓨터_전체보기',
        'http://popcornpc.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=11040&game=&sprice=&eprice=&event_no=&pc_title=',
        'http://popcornpc.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=11039&game=&sprice=&eprice=&event_no=&pc_title=라이젠컴퓨터_(3세대)',
        'http://popcornpc.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=11135&game=&sprice=&eprice=&event_no=&pc_title=본체 모니터패키지',
        'http://popcornpc.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=11254&game=&sprice=&eprice=&event_no=&pc_title=사무',
        'http://popcornpc.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=11019&game=&sprice=&eprice=&event_no=&pc_title=사무 / 가정용 / 멀티미디어',
        'http://popcornpc.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=11021&game=&sprice=&eprice=&event_no=&pc_title=3D게임 / 디자인 / 개인방송'])

        for link in url:
            driver.get(link)
            time.sleep(2)
            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            for name in soup.select('tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(2) > td > b > a > font:nth-child(1)'):
                ws.Cells(i,1).Value=name.text.strip()
                i+=1
                cnt+=1
            i-=cnt
            for price in soup.select('tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(3) > td > a'):
                ws.Cells(i,2).Value=price.text.strip()
                i+=1
            i-=cnt
            for info in soup.select('tbody > tr > td > table:nth-child(2) > tbody > tr > td > table > tbody > tr > td > div'):
                ws.Cells(i,j).Value=info.text.strip()
                j+=1
                if '출장' in info.text.strip():
                    i+=1
                    j=3
            cnt=0
        
        self.plainTextEdit.appendPlainText(time.strftime('%H%M%S')+"팝콘피씨완료")
        return True

    ##컴마왕

    def commawang(self):
        ws=wb.Worksheets('컴마왕')
        i=2
        cnt=0
        j=3

        url=(['http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=9270&game=&sprice=&eprice=&event_no=&pc_title=컴마왕스튜디오 월간추천견적&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=9063&game=&sprice=&eprice=&event_no=&pc_title=20만원대 기본웹서핑용&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=7823&game=&sprice=&eprice=&event_no=&pc_title=30만원대 사무용&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=8726&game=&sprice=&eprice=&event_no=&pc_title=40만원대 기본게임용&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=8727&game=&sprice=&eprice=&event_no=&pc_title=50만원대 하급게임용&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=8613&game=&sprice=&eprice=&event_no=&pc_title=60만원대 중급게임용&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=8831&game=&sprice=&eprice=&event_no=&pc_title=70만원대 상급게임용&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=8832&game=&sprice=&eprice=&event_no=&pc_title=80만원대 고급게임용&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=8081&game=&sprice=&eprice=&event_no=&pc_title=90만원대 최고급게임용&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=8819&game=&sprice=&eprice=&event_no=&pc_title=100만원대 이상 전문가용&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=9056&game=&sprice=&eprice=&event_no=&pc_title=150만원대 하이엔드 방송용&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=9065&game=&sprice=&eprice=&event_no=&pc_title=250만원대 판타스틱 고사양&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=8780&game=&sprice=&eprice=&event_no=&pc_title=오버클럭 PC&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=9060&game=&sprice=&eprice=&event_no=&pc_title=일체형 수랭 PC&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=9053&game=&sprice=&eprice=&event_no=&pc_title=커스텀 수냉 PC&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=9205&game=&sprice=&eprice=&event_no=&pc_title=라이젠 3세대 PC&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=9240&game=&sprice=&eprice=&event_no=&pc_title=인텔 10세대 PC&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=8890&game=&sprice=&eprice=&event_no=&pc_title=윈도우10 탑재 PC&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=&cate2=8909&game=&sprice=&eprice=&event_no=&pc_title=모니터 본체 패키지&origin_ctgr1=&origin_ctgr2=&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=6573&cate2=8890&game=&sprice=700000&eprice=899999&event_no=&pc_title=70-80만원대 탑재PC&origin_ctgr1=9003&origin_ctgr2=9005&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=6573&cate2=8890&game=&sprice=900000&eprice=1099999&event_no=&pc_title=90-100만원대 탑재PC&origin_ctgr1=9003&origin_ctgr2=9006&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=6573&cate2=8890&game=&sprice=1100000&eprice=1499999&event_no=&pc_title=110-140만원대 탑재PC&origin_ctgr1=9003&origin_ctgr2=9007&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=6573&cate2=8890&game=&sprice=1500000&eprice=1999999&event_no=&pc_title=150-190만원대 탑재PC&origin_ctgr1=9003&origin_ctgr2=9207&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=6573&cate2=8890&game=&sprice=2000000&eprice=2147483647&event_no=&pc_title=200만원 이상 패키지&origin_ctgr1=9003&origin_ctgr2=9208&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=6573&cate2=8909&game=&sprice=800000&eprice=1099999&event_no=&pc_title=80-100만원대 패키지&origin_ctgr1=9010&origin_ctgr2=9013&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=6573&cate2=8909&game=&sprice=1100000&eprice=1399999&event_no=&pc_title=110-130만원대 패키지&origin_ctgr1=9010&origin_ctgr2=9014&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=6573&cate2=8909&game=&sprice=1400000&eprice=1999999&event_no=&pc_title=140-190만원대 패키지&origin_ctgr1=9010&origin_ctgr2=9015&type=',
        'http://www.commawang.co.kr/skin/shop/basic/system_list_include_plist.php?group_no=&group_type=&cate1=6573&cate2=8909&game=&sprice=2000000&eprice=2147483647&event_no=&pc_title=200만원 이상 패키지&origin_ctgr1=9010&origin_ctgr2=9017&type='])

        for link in url:
            driver.get(link)
            time.sleep(2)
            html=driver.page_source
            soup=BeautifulSoup(html,'html.parser')
            for name in soup.select('tbody > tr > td > table:nth-child(1) > tbody > tr:nth-child(2) > td > b > a > font:nth-child(1)'):
                ws.Cells(i,1).Value=name.text.strip()
                i+=1
                cnt+=1
            i-=cnt
            for price in soup.select('tbody > tr > td > table:nth-child(3) > tbody > tr:nth-child(2) > td > a'):
                ws.Cells(i,2).Value=price.text.strip()
                i+=1
            i-=cnt
            for info in soup.select('tbody > tr > td > table:nth-child(2) > tbody > tr > td > span'):
                ws.Cells(i,j).Value=info.text.strip()
                j+=1
                if "스트리머" in info.text.strip():
                    i+=1
                    j=3
            cnt=0

        self.plainTextEdit.appendPlainText(time.strftime('%H%M%S')+"컴마왕완료")
        return True


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
