# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'price.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 483)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 563, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AssacomButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.AssacomButton.setObjectName("AssacomButton")
        self.horizontalLayout.addWidget(self.AssacomButton)
        self.BlueitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.BlueitButton.setObjectName("BlueitButton")
        self.horizontalLayout.addWidget(self.BlueitButton)
        self.OhmypcButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.OhmypcButton.setObjectName("OhmypcButton")
        self.horizontalLayout.addWidget(self.OhmypcButton)
        self.ComzipButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ComzipButton.setObjectName("ComzipButton")
        self.horizontalLayout.addWidget(self.ComzipButton)
        self.WanggapcButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.WanggapcButton.setObjectName("WanggapcButton")
        self.horizontalLayout.addWidget(self.WanggapcButton)
        self.PopconpcButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PopconpcButton.setObjectName("PopconpcButton")
        self.horizontalLayout.addWidget(self.PopconpcButton)
        self.CommawangButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.CommawangButton.setObjectName("CommawangButton")
        self.horizontalLayout.addWidget(self.CommawangButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 160, 531, 251))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.CPUText = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.CPUText.setObjectName("CPUText")
        self.horizontalLayout_2.addWidget(self.CPUText)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.GPUText = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.GPUText.setObjectName("GPUText")
        self.horizontalLayout_2.addWidget(self.GPUText)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_2.addWidget(self.plainTextEdit)
        self.AllButton = QtWidgets.QPushButton(self.centralwidget)
        self.AllButton.setGeometry(QtCore.QRect(260, 120, 75, 23))
        self.AllButton.setObjectName("AllButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AssacomButton.setText(_translate("MainWindow", "아싸컴"))
        self.BlueitButton.setText(_translate("MainWindow", "블루아이티"))
        self.OhmypcButton.setText(_translate("MainWindow", "오마이피씨"))
        self.ComzipButton.setText(_translate("MainWindow", "컴집"))
        self.WanggapcButton.setText(_translate("MainWindow", "왕가피씨"))
        self.PopconpcButton.setText(_translate("MainWindow", "팝콘피씨"))
        self.CommawangButton.setText(_translate("MainWindow", "컴마왕"))
        self.label.setText(_translate("MainWindow", "CPU :"))
        self.label_2.setText(_translate("MainWindow", "GPU"))
        self.label_3.setText(_translate("MainWindow", "로그"))
        self.AllButton.setText(_translate("MainWindow", "모두수집"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
